export const products = [
    {category: "Fruits", price: "$1", stocked: false, name: "Apple"},
    {category: "Fruits", price: "$1", stocked: true, name: "Dragonfruit"},
    {category: "Fruits", price: "$2", stocked: false, name: "Passionfruit"},
    {category: "Vegetables", price: "$2", stocked: true, name: "Spinach"},
    {category: "Vegetables", price: "$4", stocked: false, name: "Pumpkin"},
    {category: "Vegetables", price: "$1", stocked: true, name: "Peas"},
    {category: "Meat", price: "$1", stocked: true, name: "Fish"},
    {category: "Meat", price: "$1", stocked: false, name: "Mutton"},
    {category: "Meats", price: "$1", stocked: true, name: "Beaf"},
    {category: "Meats", price: "$1", stocked: true, name: "Fish"},
    {category: "Meats", price: "$1", stocked: false, name: "Mutton"},
    {category: "Meats", price: "$1", stocked: true, name: "Beaf"},
    {category: "Meatd", price: "$1", stocked: true, name: "Fish"},
    {category: "Meatd", price: "$1", stocked: false, name: "Mutton"},
    {category: "Meatd", price: "$1", stocked: true, name: "Beaf"},
]
